TT-JustBlogExample/FA.JustBlog/Areas/Admin/Controllers/PostController.cs
using FA.JustBlog.Areas.Admin.Data.IRepositories;
using FA.JustBlog.Core.Context;
using FA.JustBlog.Core.Models;
using FA.JustBlog.Services ;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace FA.JustBlog.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class PostController : Controller
    {
        private readonly IPostRepository _postRepository;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly FA.JustBlog.Core.IRepositories.ICategoryRepository _categoryRepository;
        public PostController(IPostRepository postRepository, UserManager<ApplicationUser> userManager, FA.JustBlog.Core.IRepositories.ICategoryRepository categoryRepository)
        {
            _userManager = userManager;
            _postRepository = postRepository;
            _categoryRepository = categoryRepository;
        }

        public IActionResult PostsAction()
        {
            ViewBag.LastestPost = _postRepository.GetLatestPost(1).ToList();
            ViewBag.MostViewedPost = _postRepository.MostViewedPosts(1).ToList();
            ViewBag.MostInterestingPost = _postRepository.GetMostInterestingPosts(1).ToList();
            ViewBag.PublishedPost = _postRepository.GetPublishedPost(1).ToList();
            ViewBag.UnPublishedPost = _postRepository.GetUn_PublishedPost(1).ToList();
            return View();
        }

        [Authorize(Roles = Roles.BlogOwner + ", " + Roles.Contribute)]
        public IActionResult Create()
        {
            List<Category> categories = _categoryRepository.GetAllCategories().ToList();
            ViewBag.Categories = categories;
            return View();
        }
        [Route("/Admin/Post/List/{page?}/{pageSize?}")]
        [HttpGet]
        public async Task<IActionResult> List(int? page, int? pageSize)
        {
            const int defaultPageSize = 5;
            const int defaultPageNumber = 1;

            var posts = _postRepository.GetAllPosts().ToList();

            page = page ?? defaultPageNumber;
            pageSize = pageSize ?? defaultPageSize;

            ViewBag.CurrentPageSize = pageSize;

            ViewBag.PageSize = new int[5] { 5, 10, 15, 20, 25 };
            var totalItems = posts.Count;
            var totalPages = (int)Math.Ceiling((double)totalItems / pageSize.Value);


            posts = posts.Skip((page.Value - 1) * pageSize.Value).Take(pageSize.Value).ToList();

            ViewBag.SelectedPageSize = pageSize;
            ViewBag.TotalPages = totalPages;
            ViewBag.CurrentPage = page;

            return View(posts);
        }


        [HttpPost]
        [Authorize]
        public IActionResult Create(Post post)
        {
            try
            {
                Post newPost = new Post
                {
                    Title = post.Title,
                    ShortDescription = post.ShortDescription,
                    PostContent = post.PostContent,
                    UrlSlug = post.UrlSlug,
                    Published = post.Published,
                    PostedOn = DateTime.Now,
                    Modified = DateTime.Now,
                    CategoryId = post.CategoryId,
                    ViewCount = 0,
                    RateCount = 0,
                    TotalRate = 0,
                    Rate = 0
                };

                _postRepository.InsertPost(newPost);
                return Redirect("List");
            }
            catch (Exception e)
            {
                ViewBag.Error = e.Message;
                return View(post);
            }
        }
        [Authorize(Roles = Roles.BlogOwner)]
        public IActionResult DeletePost(int id)
        {
            var post = _postRepository.FindPost(id);
            if (post == null)
            {
                return NotFound();
            }
            _postRepository.DeletePost(post);

            return RedirectToRoute("Admin_AllList");
        }
        [Authorize(Roles = Roles.BlogOwner)]
        [HttpGet]
        public IActionResult Update(int id)
        {
            var post = _postRepository.FindPost(id);
            List<Category> categories = _categoryRepository.GetAllCategories().ToList();
            ViewBag.Categories = categories;
            if (post == null)
            {
                return NotFound();
            }
            return View(post);
        }
        [HttpPost]
        [Authorize(Roles = Roles.BlogOwner)]
        public IActionResult Update(Post post)
        {
            _postRepository.UpdatePost(post);
            return RedirectToRoute("Admin_AllList");            
        }

        public JsonResult ListUsingJqGrid()
        {
            List<Post> posts = _postRepository.GetAllPosts().ToList();
            return Json(new { rows = posts, total = 1, page = 1, records = posts.Count });
            //return Json(posts);
        }


    }
}

TT-JustBlogExample/FA.JustBlog/Areas/Admin/Controllers/RoleController.cs
using FA.JustBlog.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace FA.JustBlog.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = Roles.BlogOwner + ", " + Roles.Admin)]
    public class RoleController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;
        public RoleController(RoleManager<IdentityRole> roleManager)
        {
            _roleManager = roleManager;
        }
        [Route("Admin/Role/List")]
        public IActionResult List()
        {   
            ViewBag.Roles = _roleManager.Roles.ToList();
            return View();
        }
        [Route("Admin/Role/Create")]
        public IActionResult Create(string roleName)
        {
            if (!string.IsNullOrEmpty(roleName))
            {
                if(_roleManager.RoleExistsAsync(roleName).Result == false)
                {
                    var role = new IdentityRole(roleName);
                    var result = _roleManager.CreateAsync(role).Result;
                    if (result.Succeeded)
                    {
                        return RedirectToAction("List");
                    }
                }
            }
            return View();
        }
        [Route("Admin/Role/Delete/{id}")]
        public IActionResult Delete(string id)
        {
            var role = _roleManager.FindByIdAsync(id).Result;
            if (role != null)
            {
                var result = _roleManager.DeleteAsync(role).Result;
                if (result.Succeeded)
                {
                    return RedirectToAction("List");
                }
            }
            return NotFound();
        }
        [HttpPost]
        [Route("Admin/Role/Edit/{id}")]
        public IActionResult Edit(string id, string roleName)
        {
            var role = _roleManager.FindByIdAsync(id).Result;
            if (role != null)
            {
                role.Name = roleName;
                return View();
            }
            return NotFound();
        }
    }
}

TT-JustBlogExample/FA.JustBlog/Areas/Admin/Controllers/UserController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using FA.JustBlog.Core.Models;
using FA.JustBlog.Models;
using Microsoft.AspNetCore.Authorization;
using FA.JustBlog.Services;
using System.Drawing;

namespace FA.JustBlog.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = Roles.BlogOwner + ", " + Roles.Admin)]
    public class UserController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        public UserController(UserManager<ApplicationUser> userManager, RoleManager<IdentityRole> roleManager)
        {
            _userManager = userManager;
            _roleManager = roleManager;
        }   
        [Route("/Admin/User/List")]
        public IActionResult List()
        {
            var users = _userManager.Users.ToList();
            List<UserWithRolesViewModel> usersWithRoles = new List<UserWithRolesViewModel>();

            // Take all roles
            var roles = _roleManager.Roles.ToList();
            ViewBag.Count = roles.Count;
            string[] rolesName = new string[roles.Count];
            for (int i = 0; i < roles.Count; i++)
            {
                rolesName[i] = roles[i].Name;
            }
            ViewBag.Roles = rolesName;

            foreach (var user in users)
            {   
                var userRoles = _userManager.GetRolesAsync(user).Result;
                usersWithRoles.Add(new UserWithRolesViewModel
                {
                    User = user,
                    Roles = userRoles
                }) ;
            }

            return View(usersWithRoles);
        }
        [HttpPost]
        [Route("/Admin/User/ActionRole")]
        public async Task<IActionResult> actionRole(string roleName, string userId)
        {
            var user = await _userManager.FindByIdAsync(userId);
            if (user == null)
            {
                return NotFound();
            }

            var userHasRole = await _userManager.IsInRoleAsync(user, roleName);
            if (userHasRole)
            {
                var result = await _userManager.RemoveFromRoleAsync(user, roleName);
                if (!result.Succeeded)
                {
                    return RedirectToAction("List");
                }
            }
            else
            {
                var result = await _userManager.AddToRoleAsync(user, roleName);
                if (!result.Succeeded)
                {
                    return RedirectToAction("List");
                }
            }

            return RedirectToAction("List");
        }
        public IActionResult ManageRoles()
        {
            var roles = _roleManager.Roles.ToList();
            ViewBag.roles = roles;
            return View();
        }
    }
}

TT-JustBlogExample/FA.JustBlog/Controllers/TagController.cs
using FA.JustBlog.Core.IRepositories;
using FA.JustBlog.Core.Models;
using FA.JustBlog.Core.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.ObjectModel;

namespace FA.JustBlog.Controllers
{
    public class TagController : Controller
    {
        private ITagRepository _context;
        private ICategoryRepository _categoryRepository;
        public TagController(ITagRepository context, ICategoryRepository categoryRepository)
        {
            _context = context;
            _categoryRepository = categoryRepository;
        }
        public IActionResult Index()
        {
            return View();
        }
        public PartialViewResult PopularTag()
        {
            //code to get tag desc by count
            List<Tag> tagList = _context.GetAllTags()
                            .OrderByDescending(p => p.Count)
                            .Take(10)
                            .ToList();

            return PartialView("_PopularTags", tagList);
        }
        [Authorize(Roles = "Contributor")]
        public IActionResult PopularTags()
        {
            List<Category> listCates = _categoryRepository.GetAllCategories().ToList();
            ViewBag.Categories = listCates;
            List<Tag> tagList = _context.GetAllTags()
                            .OrderByDescending(p => p.Count)
                            .Take(10)
                            .ToList();
            ViewBag.tags = tagList;
            return View();
        }
    }
}

TT-JustBlogExample/FA.JustBlog/Areas/Admin/Views/Post/Details.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

TT-JustBlogExample/FA.JustBlog/Areas/Admin/Views/Post/List.cshtml
@{
    ViewBag.Title = "Post List";
}

@model IEnumerable<Post>;

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <!-- Include Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <style>
        /* Custom CSS for table */
        .table th, .table td {
            vertical-align: middle;
        }

        .pagination-container {
            margin-top: 20px;
            text-align: center;
        }

        .pagination .page-item {
            display: inline-block;
            margin: 0 5px;
        }

        .pagination .page-link {
            padding: 8px 16px;
            color: #007bff;
            border: 1px solid #007bff;
            border-radius: 4px;
            transition: background-color 0.3s;
        }

            .pagination .page-link:hover {
                background-color: #007bff;
                color: #fff;
            }

        .pagination .page-item.active .page-link {
            background-color: #007bff;
            color: #fff;
            border-color: #007bff;
        }

    </style>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="#">JustBlog</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("List", "Post")">Posts</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("List", "Category")">Categories</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("List", "Tag")">Tags</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("List", "User")">Users</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("List", "Role")">Roles</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container-fluid">
        <h1 class="my-4">Post List</h1>
        <a href="@Url.RouteUrl("Admin_Create")" class="btn btn-success">Create New Post</a>
        <a href="@Url.Action("Index", "Post")" class="btn btn-success">Back</a>
        <div class="mt-3">
            @{
                    <div class="page-size-container">
                       <label for="pageSize">Page Size:</label>
                       <form id="formSize" asp-action="List" asp-controller="Post">
                            <select name="pageSize" onchange="submit(document.getElementById('formSize'))">
                            @{
                                foreach (var item in ViewBag.PageSize)
                                {
                                    if (item == ViewBag.CurrentPageSize && ViewBag.CurrentPageSize != null )
                                    {
                                        <option value="@item" selected>@item</option>

                                    } else
                                    {
                                        <option value="@item">@item</option>

                                    }
                                }
                                }
                            </select>
                       </form>
                    </div>
            }
        </div>

        <div class="row mt-4">
            <div class="col-md-12">
                <div class="table-responsive">
                    <table class="table table-bordered table-hover">
                        <thead class="thead-dark">
                            <tr>
                                <th>ID</th>
                                <th>Title</th>
                                <th>Short Description</th>
                                <th>Content</th>
                                <th>URL Slug</th>
                                <th>Published</th>
                                <th>Posted On</th>
                                <th>Modified</th>
                                <th>Category ID</th>
                                <th>View Count</th>
                                <th>Rate Count</th>
                                <th>Total Rate</th>
                                <th>Rate</th>
                                <th>Action</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            <!-- Replace the data here with your actual data from the database -->
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>@item.Id</td>
                                    <td>@item.Title</td>
                                    <td>@Html.Raw(item.ShortDescription)</td>
                                    <td>@Html.Raw(item.PostContent)</td>
                                    <td>@item.UrlSlug</td>
                                    <td>@item.Published</td>
                                    <td>@item.PostedOn</td>
                                    <td>@item.Modified</td>
                                    <td>@item.CategoryId</td>
                                    <td>@item.ViewCount</td>
                                    <td>@item.RateCount</td>
                                    <td>@item.TotalRate</td>
                                    <td>@item.Rate</td>
                                    <td><a href="@Url.RouteUrl("Admin_Delete", new {Id = @item.Id})" onclick=popupConfirm() id="confirmDelete" class="btn btn-danger">Delete</a></td>
                                    <td><a href="@Url.RouteUrl("Admin_Update", new {Id = @item.Id})" class="btn btn-primary">Edit</a></td>
                                </tr>
                            }
                            <!-- Repeat this row for each post in your database -->
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <nav aria-label="Page navigation">
        <div class="pagination-container">
            <ul class="pagination justify-content-center">
                @for (int i = 1; i <= ViewBag.TotalPages; i++)
                {
                    <li class="page-item @(i == ViewBag.CurrentPage ? "active" : "")">
                        <a class="page-link" href="@Url.RouteUrl("Admin_Paging", new { page = i, pageSize = ViewBag.SelectedPageSize })">@i</a>
                    </li>
                }
            </ul>
        </div>
    </nav>


    <script>
        function submit(form) {
            form.submit();
        }
        function popupConfirm() {
            if (confirm("Are you sure you want to delete this post?")) {
                return true;
            } else {
                return false;
            }
        }
        }
    </script>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.14.4/jquery.min.js"></script>
    <!-- Include Bootstrap JS (optional) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

TT-JustBlogExample/FA.JustBlog/Areas/Admin/Views/Post/ListUsingJqGrid.cshtml
@{
    ViewData["Title"] = "ListUsingJqGrid";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ViewData["Title"]</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/themes/base/jquery-ui.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/free-jqgrid/4.15.6/css/ui.jqgrid.min.css" />
    <style>
        /* Add custom CSS here */
    </style>
</head>
<body>
    <table id="jqGrid"></table>
    <div id="jqGridPager"></div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/free-jqgrid/4.15.6/jquery.jqgrid.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/free-jqgrid/4.15.6/plugins/jquery.jqgrid.showhidecolumns.min.js"></script>

    <script>
        $(function () {
            $("#jqGrid").jqGrid({
                JsonReader: {
                    repeatitems: false,
                    Id: 'Id'
                },
                url: '@Url.RouteUrl("Admin_jqGrid")',
                datatype: 'json',
                mType: "GET",
                colNames: ['Id', 'Title', 'Short Description', 'Content', 'URL Slug', 'Published', 'Posted On', 'Modified', 'Category ID', 'View Count', 'Rate Count', 'Total Rate', 'Rate'],
                colModel: [
                    { name: 'Id', width: 50 },
                    { name: 'Title', width: 200 },
                    { name: 'ShortDescription', width: 200 },
                    { name: 'PostContent', width: 300 },
                    { name: 'UrlSlug', width: 150 },
                    { name: 'Published', width: 100, formatter: 'checkbox' },
                    { name: 'PostedOn', width: 150 },
                    { name: 'Modified', width: 150 },
                    { name: 'CategoryId', width: 100 },
                    { name: 'ViewCount', width: 100 },
                    { name: 'RateCount', width: 100 },
                    { name: 'TotalRate', width: 100 },
                    { name: 'Rate', width: 100 }
                ],
                data: posts,
                pager: '#jqGridPager',
                viewrecords: true,
                caption: 'List of Posts'
            });
        });
    </script>

</body>
</html>

TT-JustBlogExample/FA.JustBlog/Areas/Admin/Views/Post/PostsAction.cshtml
@{
    ViewData["Title"] = "List of posts";
    List<Post> LastestPost = ViewBag.LastestPost as List<Post>;
    List<Post> MostViewedPost = ViewBag.MostViewedPost as List<Post>;
    List<Post> MostInterestingPost = ViewBag.MostInterestingPost as List<Post>;
    List<Post> publishedPost = ViewBag.PublishedPost as List<Post>;
    List<Post> unpublishedPost = ViewBag.UnpublishedPost as List<Post>;
    List<List<Post>> posts = new List<List<Post>> { LastestPost, MostViewedPost, MostInterestingPost, publishedPost, unpublishedPost };
    List<String> titles = new List<String> { "Lastest Posts", "Most Viewed Posts", "Most Interesting Posts", "Published Posts", "Unpublished Posts" };
}
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Admin Areas</title>
    <link rel="icon" type="image/x-icon" href="/admin/assets/favicon.ico" />
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v5.15.4/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="/admin/css/styles.css" rel="stylesheet" />
</head>
<body>
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
        <div class="container px-4 px-lg-5">
            <a class="navbar-brand" href="index.html">Start Bootstrap</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                Menu
                <i class="fas fa-bars"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ms-auto py-4 py-lg-0">
                    <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="Index">Home</a></li>
                    <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="Home/AboutCard">Create</a></li>
                    <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="post.html">List All Post</a></li>
                    <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="contact.html">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <!-- Page Header-->
    <header class="masthead" style="background-image: url('/admin/assets/img/home-bg.jpg')">
        <div class="container position-relative px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <div class="site-heading">
                        <h1>Admin Areas</h1>
                        <span class="subheading">A Blog Theme by Start Bootstrap</span>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <!-- Main Content-->
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                @for (var i = 0; i < posts.Count; i++)
                {
                    <div class="post-preview">
                        <a href="post.html">
                            <h2 class="post-title">@titles[i]</h2>
                        </a>
                        @foreach (var post in posts[i])
                        {
                            <hr class="my-4" />
                            <div class="post-preview">
                                <a href="@Url.Action("Details", "Post", new { year = post.PostedOn.Year, month = post.PostedOn.Month.ToString("00"), Title = post.Title })">
                                    <h2 class="post-title">@post.Title</h2>
                                </a>
                                @{
                                    var timePost = post.PostedOn;
                                    int time = (int)(DateTime.Now - timePost).TotalHours;
                                    if (time < 1)
                                    {
                                        time = (int)(DateTime.Now - timePost).TotalMinutes;
                                        <sub class="post-subtitle">Posted @time minutes ago with rate @post.Rate by @post.ViewCount view(s)</sub>
                                    }
                                    else if (time < 24)
                                    {
                                        <sub class="post-subtitle">Posted @time hours ago with rate @post.Rate by @post.ViewCount view(s)</sub>
                                    }
                                    else if (time < 48)
                                    {
                                        <sub class="post-subtitle">Posted yesterday with rate @post.Rate by @post.ViewCount view(s)</sub>
                                    }
                                    else
                                    {
                                        <sub class="post-subtitle">Posted on @post.PostedOn with rate @post.Rate by @post.ViewCount view(s)</sub>
                                    }
                                }
                                <p>
                                    @post.PostContent
                                </p>
                                <div>Category MVC</div>
                                <p>
                                    Tags:
                                    @foreach (var tag in new[] { "ado.net", "javascript", "mvc", "Csharp", "entity framework" })
                                    {
                                        <button style="background-color: black">
                                            @Html.ActionLink(tag, "Tag", "Find", new { tag }, new { @style = "color: white; text-decoration: underline" })
                                        </button>
                                    }
                                </p>
                            </div>
                        }
                        <div class="d-flex justify-content-end mb-4"><a class="btn btn-primary text-uppercase" href="#!">Older Posts →</a></div>
                    </div>
                }
            </div>
        </div>
    </div>


    <!-- Footer-->
    @Html.Partial("_PartialFooter")
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="/admin/js/scripts.js"></script>
</body>
</html>